version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mbectemi
      POSTGRES_DB: nestJs-221
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"  
    depends_on:
      - db
  api:
    build:
      context: C:\Users\pc\Documents\NestJsBackend
      dockerfile: Dockerfile
    command: sh -c "npx prisma db push && npm run start:dev"  
    volumes:
      - C:\Users\pc\Documents\NestJsBackend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Mbectemi@db:5432/nestJs-221?schema=public
      JSECRET_ACCESS_TOKEN: ${JSECRET_ACCESS_TOKEN}
      JSECRET_TIME_TO_EXPIRE: 1d
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app

  web:
    build:
      context: C:\Users\pc\Documents\JS\gestion-dette-221-react
      dockerfile: Dockerfile
    volumes:
      - C:\Users\pc\Documents\JS\gestion-dette-221-react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_BASE_URL: http://localhost:3000/api
    depends_on:
      - api
    working_dir: /app
    command: npm run dev

volumes:
  postgres_data:
